export const blogConstant = {
  FETCH_BLOG_POST_REQUEST: 'FETCH_BLOG_POST_REQUEST',
  FETCH_BLOG_POST_SUCCESS: 'FETCH_BLOG_POST_SUCCESS',
  FETCH_BLOG_POST_FAILURE: 'FETCH_BLOG_POST_FAILURE',
  FETCH_BLOG_POST_IMAGE_REQUEST:'FETCH_BLOG_POST_IMAGE_REQUEST',
  FETCH_BLOG_POST_IMAGE_SUCCESS:'FETCH_BLOG_POST_IMAGE_SUCCESS',
  FETCH_BLOG_POST_IMAGE_FAILURE:'FETCH_BLOG_POST_IMAGE_FAILURE',
};

export const postConstant = {
  FETCH_POST_REQUEST: 'FETCH_POST_REQUEST',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  FETCH_POST_FAILURE: 'FETCH_POST_FAILURE',
};
