export const blogConstant = {
    FETCH_BLOG_POST_REQUEST: 'FETCH_BLOG_POST_REQUEST',
    FETCH_BLOG_POST_SUCCESS: 'FETCH_BLOG_POST_SUCCESS',
    FETCH_BLOG_POST_FAILURE: 'FETCH_BLOG_POST_FAILURE'
}

